// <auto-generated />
using CPRG214.MvcCore.Assignment2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CPRG214.MvcCore.Assignment2.Data.Migrations
{
    [DbContext(typeof(AssetsContext))]
    partial class AssetContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CPRG214.MvcCore.Assignment2.Domain.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AssetTypeID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssetTypeID");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssetTypeID = 100,
                            Description = "The most powerful computer you have ever owned",
                            Manufacturer = "Dell",
                            Model = "SX-10",
                            SerialNumber = "100123963",
                            TagNumber = "abc123"
                        },
                        new
                        {
                            Id = 2,
                            AssetTypeID = 200,
                            Description = "The best monitor for developer",
                            Manufacturer = "LG",
                            Model = "LG-X3",
                            SerialNumber = "200123963",
                            TagNumber = "def456"
                        },
                        new
                        {
                            Id = 3,
                            AssetTypeID = 300,
                            Description = "The most stylish phone for the ladies",
                            Manufacturer = "Cisco",
                            Model = "Cisco-100",
                            SerialNumber = "300123963",
                            TagNumber = "ghi789"
                        });
                });

            modelBuilder.Entity("CPRG214.MvcCore.Assignment2.Domain.AssetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AssetTypes");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Name = "Computers by Dell"
                        },
                        new
                        {
                            Id = 200,
                            Name = "Monitor by LG"
                        },
                        new
                        {
                            Id = 300,
                            Name = "Phones by Cisco"
                        });
                });

            modelBuilder.Entity("CPRG214.MvcCore.Assignment2.Domain.Asset", b =>
                {
                    b.HasOne("CPRG214.MvcCore.Assignment2.Domain.AssetType", "Assets")
                        .WithMany("Assets")
                        .HasForeignKey("AssetTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
